# Simplified Redis configuration for debugging
master:
  persistence:
    enabled: false  # Disable persistence to simplify deployment
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  # Add some custom configurations that do not affect startup speed
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "redis"
      effect: "NoSchedule"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: redis
            topologyKey: kubernetes.io/hostname

replica:
  replicaCount: 2
  persistence:
    enabled: false  # Disable persistence
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  # Replicas use the same scheduling configuration
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "redis"
      effect: "NoSchedule"

auth:
  enabled: true
  password: "simple123"

metrics:
  enabled: false  # Temporarily disable metrics

# Additional configurations that do not affect startup
commonLabels:
  app: redis-cluster
  environment: test
  team: platform

# Service configuration
service:
  type: ClusterIP
  port: 6379
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    prometheus.io/scrape: "false"

# Network policy configuration
networkPolicy:
  enabled: false
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: shared-services

# Redis configuration parameters (do not affect startup speed)
redis:
  configmap: |
    # Custom Redis configuration
    maxmemory-policy allkeys-lru
    timeout 300
    tcp-keepalive 60
    # Disable some heavy operations
    save ""
    
# Security context
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
  runAsNonRoot: true
