# a mcp server to get authenticated bio info
# https://github.com/genomoncology/biomcp
type: stdio
name: biomcp
params:
  command: uv
  args:
    - "run"
    - "--with"
    - "biomcp-python"
    - "biomcp"
    - "run"
client_session_timeout_seconds: 20
cache_tools_list: true