# Fetch 抓取网页并获得 raw HTML 或者转化后的 markdown
# https://modelscope.cn/mcp/servers/@modelcontextprotocol/fetch
type: stdio
name: fetch
params:
  command: python
  args:
    - "-m"
    - "mcp_server_fetch"
client_session_timeout_seconds: 10
cache_tools_list: true