# Figma
# https://www.modelscope.cn/mcp/servers/@GLips/Figma-Context-MCP
# this is good, but the evaluation is quite haard ... 
type: stdio
name: Figma
params:
  command: npx
  args:
    - "-y"
    - "figma-developer-mcp"
    - "--figma-api-key=figdF_E4gcLjqosyeZ4ddbzqcNuDPCQjlCauKKMZoSUpHY"
    - "--stdio"
client_session_timeout_seconds: 100
cache_tools_list: true