# firecrawl搜索
# https://github.com/mendableai/firecrawl-mcp-server
# good performance but paid
type: stdio
name: firecrawl
params:
  command: npx
  args:
    - "-y"
    - "firecrawl-mcp"
  env:
    FIRECRAWL_API_KEY: "${token.firecrawl_token}"
cache_tools_list: true