# 微信读书
# https://www.modelscope.cn/mcp/servers/@package/mcp-server-weread
type: stdio
name: weread
params:
  command: npx
  args:
    - "-y"
    - "weread"
  env:
    CC_URL: "xxxxxx"
    CC_ID:  "xxxxxx"
    CC_PASSWORD: "xxxxx"
client_session_timeout_seconds: 50
cache_tools_list: true