# Fetch latex source from arxiv
# Source: https://github.com/takashiishida/arxiv-latex-mcp
# Toolathlon Version: The same
type: stdio
name: arxiv-latex
params:
  command: uv
  args:
    - "--directory"
    - "${local_servers_paths}/arxiv-latex-mcp"
    - "run"
    - "arxiv-latex-mcp.py"
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 10
cache_tools_list: true 