# EdgeOne Pages - 用于将 HTML 内容部署到 EdgeOne Pages 并获取公开可访问 URL
# https://github.com/TencentEdgeOne/edgeone-pages-mcp/tree/main
type: stdio
name: edgeone
params:
  command: npx
  args:
    - "edgeone-pages-mcp"
  env:
    EDGEONE_PAGES_API_TOKEN: "${token.edgeone_token}"
client_session_timeout_seconds: 100
cache_tools_list: true