# Excel
# Source: https://github.com/haris-musa/excel-mcp-server
# Toolathlon Version: The same
type: stdio
name: excel
params:
  command: uv
  args:
    - "run"
    - "excel-mcp-server"
    - "stdio"
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 100
cache_tools_list: true