# 文件系统服务器 - 用于读写文件
# https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem
type: stdio
name: firecrawl
params:
  command: npx
  args:
    - "-y"
    - "firecrawl-mcp"
  env:
    FIRECRAWL_API_KEY: "${token.firecrawl_token}"
cache_tools_list: true