# check local git status
# https://github.com/modelcontextprotocol/servers/tree/main/src/git
type: stdio
name: git
params:
  command: uv
  args:
    - "run"
    - "-m"
    - "mcp_server_git"
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 10
cache_tools_list: true