# GitHub API 集成
# https://github.com/modelcontextprotocol/servers/tree/main/src/github
type: stdio
name: github
params:
  command: podman
  args:
    - "run"
    - "-i"
    - "--rm"
    - "-e"
    - "GITHUB_PERSONAL_ACCESS_TOKEN"
    - "ghcr.io/github/github-mcp-server"
  env:
    GITHUB_PERSONAL_ACCESS_TOKEN: "${token.github_token}"
client_session_timeout_seconds: 50
cache_tools_list: true