# headless gmail integration
# https://github.com/GongRzhe/Gmail-MCP-Server
type: stdio
name: gmail
params:
  command: npx
  args:
    - "-y"
    - "@gongrzhe/server-gmail-autoauth-mcp"
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 10
cache_tools_list: true