# k8s
# https://github.com/Flux159/mcp-server-kubernetes/blob/main/ADVANCED_README.md
type: stdio
name: k8s
params:
  command: npx
  args:
    - "-y"
    - "mcp-server-kubernetes"
  env:
    KUBECONFIG_PATH: "${token.kubeconfig_path}"
client_session_timeout_seconds: 10
cache_tools_list: true