# 网页内容抓取并转换为各种格式（HTML、JSON、Markdown、纯文本）
# https://www.modelscope.cn/mcp/servers/@tokenizin-agency/mcp-npx-fetch
# seems to be an updated version of fetch
type: stdio
name: fetch
params:
  command: npx
  args:
    - "-y"
    - "@tokenizin/mcp-npx-fetch"
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 100
cache_tools_list: true