# a ppt mcp server
# https://github.com/GongRzhe/Office-PowerPoint-MCP-Server
type: stdio
name: pptx
params:
  command: uvx
  args:
    - "--from"
    - "office-powerpoint-mcp-server"
    - "ppt_mcp_server"
client_session_timeout_seconds: 10
cache_tools_list: true