# a ppt mcp server
# Source: https://github.com/GongRzhe/Office-PowerPoint-MCP-Server
# Toolathlon Version: The same
type: stdio
name: pptx
params:
  command: uvx
  args:
    - "--from"
    - "office-powerpoint-mcp-server"
    - "ppt_mcp_server"
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 10
cache_tools_list: true