# 访问 shadcn/ui 组件文档和示例
# https://github.com/ymadd/shadcn-ui-mcp-server
type: stdio
name: shadcn_ui
params:
  command: npx
  args:
    - "-y"
    - "shadcn-ui-mcp-server"
  cwd: "${agent_workspace}"
cache_tools_list: true