# snowflake
# Source: https://github.com/isaacwasserman/mcp-snowflake-server
# Toolathlon Version: https://github.com/lockon-n/mcp-snowflake-server
type: stdio
name: snowflake
params:
  command: uvx
  args:
    - "mcp_snowflake_server"
    - "--account"
    - "${token.snowflake_account}"
    - "--warehouse"
    - "${token.snowflake_warehouse}"
    - "--user"
    - "${token.snowflake_user}"
    - "--password"
    - "${token.snowflake_password}"
    - "--role"
    - "${token.snowflake_role}"
    - "--database"
    - "${token.snowflake_database}"
    - "--schema"
    - "${token.snowflake_schema}"
    - "--allowed_databases"
    - "${token.snowflake_op_allowed_databases}"
    - "--allow_write"
    - "--exclude-json-results"
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 120
cache_tools_list: true