# 在解决复杂问题时为 Claude 提供了一个专门的空间来进行结构化思考
# https://www.modelscope.cn/mcp/servers/@cgize/claude-mcp-think-tool
type: stdio
name: think-tool
params:
  command: npx
  args:
    - "-y"
    - "@cgize/mcp-think-tool"
  pollingInterval: 30000
  startupTimeout: 30000
  restartOnFailure: true
client_session_timeout_seconds: 100
cache_tools_list: true