
# https://github.com/bytedance/UI-TARS-desktop/tree/main/packages/agent-infra/mcp-servers/browser
type: stdio
name: ui_tars_browser
params:
  command: npx
  args:
    - "-y"
    - "@agent-infra/mcp-server-browser"
client_session_timeout_seconds: 30
cache_tools_list: true