# Yahoo Finance
# Source: https://github.com/Alex2Yang97/yahoo-finance-mcp
# Toolathlon Version: https://github.com/lockon-n/yahoo-finance-mcp
type: stdio
name: yahoo-finance
params:
  command: uv
  args:
    - "run"
    - "${local_servers_paths}/yahoo-finance-mcp/server.py"
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 60
cache_tools_list: true