# this server need to be installed locally
# see `install_records/yahoo_finance.md`
type: stdio
name: yahoo-finance
params:
  command: uv
  args:
    - "run"
    - "${local_servers_paths}/yahoo-finance-mcp/server.py"
client_session_timeout_seconds: 60
cache_tools_list: true