# YouTube Transcript
# Source: https://github.com/jkawamoto/mcp-youtube-transcript
# Toolathlon Version: The same
type: stdio
name: youtube-transcript
params:
  command: uvx
  args:
    - "--from"
    - "mcp-youtube-transcript"
    - "mcp-youtube-transcript"
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 10
cache_tools_list: true