# mcp 4 youtube
# Source: https://github.com/ZubeidHendricks/youtube-mcp-server
# Toolathlon Version: https://github.com/lockon-n/youtube-mcp-server
type: stdio
name: youtube
params:
  command: node
  args:
    - "${local_servers_paths}/youtube-mcp-server/dist/index.js"
  env:
    YOUTUBE_API_KEY: "${token.google_cloud_console_api_key}"
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 20
cache_tools_list: true