# mcp 4 youtube
# https://github.com/ZubeidHendricks/youtube-mcp-server
# this servers has been mostly fixed, however, the transcript retrieval is still buddy .. .idk why
type: stdio
name: youtube
params:
  command: node
  args:
    - "${local_servers_paths}/youtube-mcp-server/dist/index.js"
  env:
    YOUTUBE_API_KEY: "${token.google_cloud_console_api_key}"
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 20
cache_tools_list: true