---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---

# ========= Production 环境 =========

# Payment Gateway 服务（正式版）
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-gateway
      env: production
      release: v1.0.0
  template:
    metadata:
      labels:
        app: payment-gateway
        env: production
        release: v1.0.0
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
          ports:
            - containerPort: 8080
          env:
            - name: LOG_LEVEL
              value: "info"
---
# User Service 服务（正式版）
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      env: production
      release: v2.3.1
  template:
    metadata:
      labels:
        app: user-service
        env: production
        release: v2.3.1
    spec:
      containers:
        - name: user-api
          image: nginx:1.14
          ports:
            - containerPort: 9090
          env:
            - name: LOG_LEVEL
              value: "info"
---
# Order Processor 服务（正式版）
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-processor
      env: production
      release: v1.5.0
  template:
    metadata:
      labels:
        app: order-processor
        env: production
        release: v1.5.0
    spec:
      containers:
        - name: order-worker
          image: nginx:1.14
          ports:
            - containerPort: 7070
          env:
            - name: LOG_LEVEL
              value: "info"
---

# ========= Dev 环境 =========

# Inventory Manager 开发版
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-manager-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-manager
      env: dev
      release: dev-latest
  template:
    metadata:
      labels:
        app: inventory-manager
        env: dev
        release: dev-latest
    spec:
      containers:
        - name: inventory-api
          image: nginx:1.14
          ports:
            - containerPort: 6060
          env:
            - name: LOG_LEVEL
              value: "debug"
