#!/usr/bin/env python3
"""
从PDF文件中提取的世界银行官方地区分类信息
用于生成准确的国家-地区映射关系
"""

def get_world_bank_region_mapping():
    """
    返回基于世界银行官方分类的国家-地区映射关系
    数据来源：world-by-region-map.pdf (World Bank Atlas of Sustainable Development Goals 2018)
    """
    
    region_mapping = {
    # --- East Asia & Pacific ---
    "American Samoa": "East Asia & Pacific",
    "Australia": "East Asia & Pacific",
    "Brunei Darussalam": "East Asia & Pacific",
    "Cambodia": "East Asia & Pacific",
    "China": "East Asia & Pacific",
    "Fiji": "East Asia & Pacific",
    "French Polynesia": "East Asia & Pacific",
    "Guam": "East Asia & Pacific",
    "Hong Kong SAR, China": "East Asia & Pacific",
    "Indonesia": "East Asia & Pacific",
    "Japan": "East Asia & Pacific",
    "Kiribati": "East Asia & Pacific",
    "Korea, Dem. People's Rep.": "East Asia & Pacific",
    "Korea, Rep.": "East Asia & Pacific",
    "Lao PDR": "East Asia & Pacific",
    "Macao SAR, China": "East Asia & Pacific",
    "Malaysia": "East Asia & Pacific",
    "Marshall Islands": "East Asia & Pacific",
    "Micronesia, Fed. Sts.": "East Asia & Pacific",
    "Mongolia": "East Asia & Pacific",
    "Myanmar": "East Asia & Pacific",
    "Nauru": "East Asia & Pacific",
    "New Caledonia": "East Asia & Pacific",
    "New Zealand": "East Asia & Pacific",
    "Northern Mariana Islands": "East Asia & Pacific",
    "Palau": "East Asia & Pacific",
    "Papua New Guinea": "East Asia & Pacific",
    "Philippines": "East Asia & Pacific",
    "Samoa": "East Asia & Pacific",
    "Singapore": "East Asia & Pacific",
    "Solomon Islands": "East Asia & Pacific",
    "Taiwan, China": "East Asia & Pacific",
    "Thailand": "East Asia & Pacific",
    "Timor-Leste": "East Asia & Pacific",
    "Tonga": "East Asia & Pacific",
    "Tuvalu": "East Asia & Pacific",
    "Vanuatu": "East Asia & Pacific",
    "Viet Nam": "East Asia & Pacific",

    # --- Europe & Central Asia ---
    "Albania": "Europe & Central Asia",
    "Andorra": "Europe & Central Asia",
    "Armenia": "Europe & Central Asia",
    "Austria": "Europe & Central Asia",
    "Azerbaijan": "Europe & Central Asia",
    "Belarus": "Europe & Central Asia",
    "Belgium": "Europe & Central Asia",
    "Bosnia and Herzegovina": "Europe & Central Asia",
    "Bulgaria": "Europe & Central Asia",
    "Channel Islands": "Europe & Central Asia",
    "Croatia": "Europe & Central Asia",
    "Cyprus": "Europe & Central Asia",
    "Czechia": "Europe & Central Asia",
    "Denmark": "Europe & Central Asia",
    "Estonia": "Europe & Central Asia",
    "Faroe Islands": "Europe & Central Asia",
    "Finland": "Europe & Central Asia",
    "France": "Europe & Central Asia",
    "Georgia": "Europe & Central Asia",
    "Germany": "Europe & Central Asia",
    "Gibraltar": "Europe & Central Asia",
    "Greece": "Europe & Central Asia",
    "Greenland": "Europe & Central Asia",
    "Hungary": "Europe & Central Asia",
    "Iceland": "Europe & Central Asia",
    "Ireland": "Europe & Central Asia",
    "Isle of Man": "Europe & Central Asia",
    "Italy": "Europe & Central Asia",
    "Kazakhstan": "Europe & Central Asia",
    "Kosovo": "Europe & Central Asia",
    "Kyrgyz Republic": "Europe & Central Asia",
    "Latvia": "Europe & Central Asia",
    "Liechtenstein": "Europe & Central Asia",
    "Lithuania": "Europe & Central Asia",
    "Luxembourg": "Europe & Central Asia",
    "Malta": "Europe & Central Asia",
    "Moldova": "Europe & Central Asia",
    "Monaco": "Europe & Central Asia",
    "Montenegro": "Europe & Central Asia",
    "Netherlands": "Europe & Central Asia",
    "North Macedonia": "Europe & Central Asia",
    "Norway": "Europe & Central Asia",
    "Poland": "Europe & Central Asia",
    "Portugal": "Europe & Central Asia",
    "Romania": "Europe & Central Asia",
    "Russian Federation": "Europe & Central Asia",
    "San Marino": "Europe & Central Asia",
    "Serbia": "Europe & Central Asia",
    "Slovak Republic": "Europe & Central Asia",
    "Slovenia": "Europe & Central Asia",
    "Spain": "Europe & Central Asia",
    "Sweden": "Europe & Central Asia",
    "Switzerland": "Europe & Central Asia",
    "Tajikistan": "Europe & Central Asia",
    "Türkiye": "Europe & Central Asia",
    "Turkmenistan": "Europe & Central Asia",
    "Ukraine": "Europe & Central Asia",
    "United Kingdom": "Europe & Central Asia",
    "Uzbekistan": "Europe & Central Asia",

    # --- Latin America & Caribbean ---
    "Antigua and Barbuda": "Latin America & Caribbean",
    "Argentina": "Latin America & Caribbean",
    "Aruba": "Latin America & Caribbean",
    "Bahamas, The": "Latin America & Caribbean",
    "Barbados": "Latin America & Caribbean",
    "Belize": "Latin America & Caribbean",
    "Bolivia": "Latin America & Caribbean",
    "Brazil": "Latin America & Caribbean",
    "British Virgin Islands": "Latin America & Caribbean",
    "Cayman Islands": "Latin America & Caribbean",
    "Chile": "Latin America & Caribbean",
    "Colombia": "Latin America & Caribbean",
    "Costa Rica": "Latin America & Caribbean",
    "Cuba": "Latin America & Caribbean",
    "Curacao": "Latin America & Caribbean",
    "Dominica": "Latin America & Caribbean",
    "Dominican Republic": "Latin America & Caribbean",
    "Ecuador": "Latin America & Caribbean",
    "El Salvador": "Latin America & Caribbean",
    "Grenada": "Latin America & Caribbean",
    "Guatemala": "Latin America & Caribbean",
    "Guyana": "Latin America & Caribbean",
    "Haiti": "Latin America & Caribbean",
    "Honduras": "Latin America & Caribbean",
    "Jamaica": "Latin America & Caribbean",
    "Mexico": "Latin America & Caribbean",
    "Nicaragua": "Latin America & Caribbean",
    "Panama": "Latin America & Caribbean",
    "Paraguay": "Latin America & Caribbean",
    "Peru": "Latin America & Caribbean",
    "Puerto Rico": "Latin America & Caribbean",
    "Sint Maarten (Dutch part)": "Latin America & Caribbean",
    "St. Kitts and Nevis": "Latin America & Caribbean",
    "St. Lucia": "Latin America & Caribbean",
    "St. Martin (French part)": "Latin America & Caribbean",
    "St. Vincent and the Grenadines": "Latin America & Caribbean",
    "Suriname": "Latin America & Caribbean",
    "Trinidad and Tobago": "Latin America & Caribbean",
    "Turks and Caicos Islands": "Latin America & Caribbean",
    "Uruguay": "Latin America & Caribbean",
    "Venezuela, RB": "Latin America & Caribbean",
    "Virgin Islands (U.S.)": "Latin America & Caribbean",

    # --- Middle East & North Africa ---
    "Afghanistan": "Middle East & North Africa",
    "Algeria": "Middle East & North Africa",
    "Bahrain": "Middle East & North Africa",
    "Djibouti": "Middle East & North Africa",
    "Egypt, Arab Rep.": "Middle East & North Africa",
    "Iran, Islamic Rep.": "Middle East & North Africa",
    "Iraq": "Middle East & North Africa",
    "Israel": "Middle East & North Africa",
    "Jordan": "Middle East & North Africa",
    "Kuwait": "Middle East & North Africa",
    "Lebanon": "Middle East & North Africa",
    "Libya": "Middle East & North Africa",
    "Malta": "Middle East & North Africa",
    "Morocco": "Middle East & North Africa",
    "Oman": "Middle East & North Africa",
    "Pakistan": "Middle East & North Africa",
    "Qatar": "Middle East & North Africa",
    "Saudi Arabia": "Middle East & North Africa",
    "Syrian Arab Republic": "Middle East & North Africa",
    "Tunisia": "Middle East & North Africa",
    "United Arab Emirates": "Middle East & North Africa",
    "West Bank and Gaza": "Middle East & North Africa",
    "Yemen, Rep.": "Middle East & North Africa",

    # --- North America ---
    "Bermuda": "North America",
    "Canada": "North America",
    "United States": "North America",

    # --- South Asia ---
    "Bangladesh": "South Asia",
    "Bhutan": "South Asia",
    "India": "South Asia",
    "Maldives": "South Asia",
    "Nepal": "South Asia",
    "Sri Lanka": "South Asia",

    # --- Sub-Saharan Africa ---
    "Angola": "Sub-Saharan Africa",
    "Benin": "Sub-Saharan Africa",
    "Botswana": "Sub-Saharan Africa",
    "Burkina Faso": "Sub-Saharan Africa",
    "Burundi": "Sub-Saharan Africa",
    "Cabo Verde": "Sub-Saharan Africa",
    "Cameroon": "Sub-Saharan Africa",
    "Central African Republic": "Sub-Saharan Africa",
    "Chad": "Sub-Saharan Africa",
    "Comoros": "Sub-Saharan Africa",
    "Congo, Dem. Rep.": "Sub-Saharan Africa",
    "Congo, Rep": "Sub-Saharan Africa",
    "Côte d'Ivoire": "Sub-Saharan Africa",
    "Equatorial Guinea": "Sub-Saharan Africa",
    "Eritrea": "Sub-Saharan Africa",
    "Eswatini": "Sub-Saharan Africa",
    "Ethiopia": "Sub-Saharan Africa",
    "Gabon": "Sub-Saharan Africa",
    "Gambia, The": "Sub-Saharan Africa",
    "Ghana": "Sub-Saharan Africa",
    "Guinea": "Sub-Saharan Africa",
    "Guinea-Bissau": "Sub-Saharan Africa",
    "Kenya": "Sub-Saharan Africa",
    "Lesotho": "Sub-Saharan Africa",
    "Liberia": "Sub-Saharan Africa",
    "Madagascar": "Sub-Saharan Africa",
    "Malawi": "Sub-Saharan Africa",
    "Mali": "Sub-Saharan Africa",
    "Mauritania": "Sub-Saharan Africa",
    "Mauritius": "Sub-Saharan Africa",
    "Mozambique": "Sub-Saharan Africa",
    "Namibia": "Sub-Saharan Africa",
    "Niger": "Sub-Saharan Africa",
    "Nigeria": "Sub-Saharan Africa",
    "Rwanda": "Sub-Saharan Africa",
    "São Tomé and Principe": "Sub-Saharan Africa",
    "Senegal": "Sub-Saharan Africa",
    "Seychelles": "Sub-Saharan Africa",
    "Sierra Leone": "Sub-Saharan Africa",
    "Somalia": "Sub-Saharan Africa",
    "South Africa": "Sub-Saharan Africa",
    "South Sudan": "Sub-Saharan Africa",
    "Sudan": "Sub-Saharan Africa",
    "Tanzania": "Sub-Saharan Africa",
    "Togo": "Sub-Saharan Africa",
    "Uganda": "Sub-Saharan Africa",
    "Zambia": "Sub-Saharan Africa",
    "Zimbabwe": "Sub-Saharan Africa",
}

    
    return region_mapping

def verify_regions():
    """验证地区映射的完整性"""
    mapping = get_world_bank_region_mapping()
    
    regions = {
        "East Asia & Pacific": [],
        "Europe & Central Asia": [],
        "Latin America & Caribbean": [],
        "Middle East & North Africa": [],
        "North America": [],
        "South Asia": [],
        "Sub-Saharan Africa": []
    }
    
    for country, region in mapping.items():
        if region in regions:
            regions[region].append(country)
    
    print("各地区国家数量统计:")
    for region, countries in regions.items():
        print(f"{region}: {len(countries)} 个国家/地区")
        
    print(f"\n总计: {len(mapping)} 个国家/地区")
    
    return regions

if __name__ == "__main__":
    verify_regions()
